# Generated by Django 5.1.3 on 2025-01-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_insurance_created_at_insurance_prediction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='prediction',
        ),
        migrations.AlterField(
            model_name='insurance',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')]),
        ),
    ]
